### ISSUE TITLE
Rewrite README for better explanation of eAbsentee

### ISSUE THREAD

**Issue by rau** [eAbsentee/eAbsentee#18]

**Comment by raunakdaga** [comment]
Mention legality - see https://github.com/TrustTheVote-Project/horatio-server/issues/60

Ask Mr. Jaquith for specific state regulation/email thread/anything that provides approval

**Comment by raunakdaga** [comment]
@waldoj Do you know the specific state regulation that allows for absentee ballots to be submitted online? I'm thinking of just writing a link to Virginia's own online ballot application as proof that online absentee ballot requests are legitimate

**Comment by waldoj** [comment]
This isn't possible because of a law or regulation — or, rather, because of one, specific, clear law or regulation — but instead because of [a 2014 interpretation of the law published by the attorney general](https://www.oag.state.va.us/files/Opinions/2014/13-111_Hinshaw.pdf), and then because of [the approval of the State Board of Elections](https://www.elections.virginia.gov/media/BoardPapers/Agendas/2015/20150513Minutes.pdf) in 2015 (on page 7). The bad news is that this does not lend itself to a neat link that somebody can follow to read and say "why, yes, I see that this is the law."
